### PR TITLE
add options for listing current config and context

### PR DESCRIPTION
**Pull request by pjaudiomv**

### CODE REVIEW

**Comment by dgershman** [comment]
lgtm, btw, Viper is cool https://github.com/spf13/viper.

**Review by dgershman — APPROVED** [review]

**Comment by dgershman** [comment]
Sorry i meant [Cobra](https://github.com/spf13/cobra).

**Comment by dgershman** [comment]
kubectl and github clis use cobra

**Comment by pjaudiomv** [comment]
Oh cool Ill have to check them out, ya it started out pretty simple but thought about using flag pkg

**Pull request merged**
