### PR TITLE
use cobra

### PR DESCRIPTION
**Pull request by pjaudiomv**
cobra is cool

### CODE REVIEW

**Comment by dgershman** [comment]
Yeah it is, I think there is even an easier way to use subcommands.  Check out how Zarf does it.  https://github.com/defenseunicorns/zarf/tree/main/src/cmd

**Comment by dgershman** [comment]
https://github.com/defenseunicorns/zarf/blob/main/src/cmd/prepare.go#L145-L149

**Comment by pjaudiomv** [comment]
> https://github.com/defenseunicorns/zarf/blob/main/src/cmd/prepare.go#L145-L149

ya I wanna use flags not sub commands 
. I did look into that though

**Comment by dgershman** [comment]
I'm cool with it is the way it is.  It might make it easier to expand upon in the future.

For example:

```shell
kxd files list
kxd files current
kxd context list
kxd context switch
kxd context current
```

Then you can alias things like (or whatever you want)

```shell
kxd f ls
kxd f c
kxd ctx ls
kxd ctx s
kxd ctx c
```

... as so on...

**Review by dgershman — APPROVED** [review]

**Pull request merged**
